version: "3"
services:

  {name}:
    build: .
    restart: always
    environment:
      - MONGO_URL=${MONGO_URL}
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules